window.jQuery = window.$ = require('jquery');
require('../js/frontend/bootstrap.bundle.min');
require('../js/frontend/jquery.appear.js');
window.Swiper = require('../js/frontend/swiper-bundle.min');
require('../js/frontend/progress-bar.min');
window.circleProgress = require('../js/frontend/circle-progress');
window.WOW = require('../js/frontend/wow.min').WOW;
require('../js/frontend/isotope.pkgd.min');
require('../js/frontend/imagesloaded.pkgd.min');
require('../js/frontend/magnific-popup.min');
require('../js/frontend/jquery.waypoints');
require('../js/frontend/effect-slicer.min');
require('../js/frontend/count-to');
require('../js/frontend/ScrollOnReveal');
window.ScrollSmoother = require('../js/frontend/ScrollSmoother.min').ScrollSmoother;
require('../js/frontend/YTPlayer.min');
require('../js/frontend/validnavs');
require('../js/frontend/gsap');
require('../js/frontend/ScrollTrigger.min');
window.SplitText = require('../js/frontend/SplitText.min').SplitText;
require('../js/frontend/main');
require('../js/frontend/gsap-init');